### ISSUE TITLE
Previews Stuck on Load Screen

### ISSUE THREAD

**Issue by codebravotech** [prismicio/gatsby-source-prismic-graphql#10]
Using these versions of the source packages, I'm not able to get previews to finish loading and display the updated page. This happens only on my built version, my development server is working correctly. 

```
    "@prismicio/gatsby-source-graphql-universal": "^3.4.9",
    "@prismicio/gatsby-source-prismic-graphql": "^3.6.7",
```

<img width="706" alt="Screen Shot 2020-07-09 at 12 42 04 PM" src="https://user-images.githubusercontent.com/42947757/87083833-1e19d300-c1e2-11ea-9d38-7d781facb8fa.png">

Any ideas what might be wrong?

**Comment by codebravotech** [comment]
For anyone else who gets strange issues with previews "getting stuck"- the problem turned out to be coming from Ghostery chrome extension, so make sure to "Trust Site"

**Comment by MarcMcIntosh** [comment]
@codebravotech 
Thanks for pointing that out :)
I'm glad you figured out the issue.
