### ISSUE TITLE
Is prismicio maintaining this project going forward?

### ISSUE THREAD

**Issue by matthewtgilbride** [prismicio/gatsby-source-prismic-graphql#14]
Hello,

The title says it all...I got here from this issue on the original maintainer's repo: https://github.com/birkir/gatsby-source-prismic-graphql/issues/217

I could have missed something in the discussion, but it is not clear to me whether or not this fork is a temporary or permanent home for the plugin going forward.

The last comment made (https://github.com/birkir/gatsby-source-prismic-graphql/issues/217#issuecomment-656412282) highlights similar hesitation I have in using Prismic for a Gatsby project for a client.

I will say...the tool seems really neat...great work so far!  Just want some clarity on what the near future holds.

Thanks.

**Comment by noblica** [comment]
Would like to know this as well. I'm approaching production, so would like to switch before that.
Also would like to know where to point my future PR fixes. I'm guessing one of these repos will be depricated...?

**Comment by MarcMcIntosh** [comment]
@matthewtgilbride and @noblica 

We at prismic had issues with the length of time it was taking to merge PR's and publish the packages on npm for this plug and it's dependancy https://github.com/prismicio/gatsby-source-graphql-universal Birkir has not been responding to our attempts at getting in contact.

So we decided to fork the repositories, fix some of the issues and publish the packages under the `@prismicio` scope. 

This solved the immediate issue of us not being able to release fixes. 

The next logical steps would be to work on making this plugin and the universal plugin easier to develop and maintain, some automated testing has been added so users can create an issue in the examples directory and open a PR which can then be fix be worked on.

> Also would like to know where to point my future PR fixes. I'm guessing one of these repos will be depricated...?

Here, please add an example that recreates the issue :)

>I will say...the tool seems really neat...great work so far! Just want some clarity on what the near future holds.
>Would like to know this as well. I'm approaching production, so would like to switch before that.

If you are deploying on gatsby cloud and want to use incremental builds i would recommend switching to https://github.com/angeloashmore/gatsby-source-prismic 

An ideal scenario would be if we could coordante changes, merge PR's and publish the packages, we did ask for permissions but we have not heard back from birkir.

I hope that answers you question :)

**Comment by matthewtgilbride** [comment]
@MarcMcIntosh seems a perfectly reasonable explanation.  Thanks!

**Comment by mjsz** [comment]
Can you add something to the gatsby plugin docs to reference this new package there?
