### ISSUE TITLE
Error: Schema must contain uniquely named types but contains multiple types named "DateTime".

### ISSUE THREAD

**Issue by matthewtgilbride** [prismicio/gatsby-source-prismic-graphql#15]
Hello,

I suspect this is an issue _only_ when one is starting with an empty prismic repository.  I found this issue on the original repo: https://github.com/birkir/gatsby-source-prismic-graphql/issues/121, but the solution there was to create some custom type, and some content, and then the issue is resolved.

That is not the case for me...I created a repo called "empty-repo" and reproduced the problem.  Then I added a custom type and some content, but still see the error.

I forked the official sample project and added a commit to demonstrate: https://github.com/matthewtgilbride/gatsby-blog

If you try and run `yarn` and then `yarn start` you will see the issue.

Thanks!

**Comment by matthewtgilbride** [comment]
I was able to fix this in my project by installing `gatsby-source-graphql` v2.6.2 and adding a resolution in my package.json
```
"resolutions": {
    "gatsby-source-graphql": "^2.6.2"
}
```

Additionally, I was able to clone this repo and bump the version, after which all tests passed.  Happy to create a PR but I don't have access.

**Comment by MarcMcIntosh** [comment]
Hi @matthewtgilbride 

Thanks for pointing that out, the version bump will need to be done on this repo https://github.com/prismicio/gatsby-source-graphql-universal

>Additionally, I was able to clone this repo and bump the version, after which all tests passed. Happy to create a PR but I don't have access

You don't have access?

https://github.com/prismicio/gatsby-source-graphql-universal

**Comment by MarcMcIntosh** [comment]
@matthewtgilbride did you publish any content?

You could use the theme command and skip adding the types and content :)
https://intercom.help/prismicio/en/articles/2933292-sample-blog-with-api-based-cms-gatsby-js

**Comment by MarcMcIntosh** [comment]
Update to `prismicio/gatsbu-source-prismic-graphql` has been published :)

**Comment by matthewtgilbride** [comment]
Thanks :)
