### ISSUE TITLE
[Discussion] - Add more info about omitPrismicScript or remove it if  preview is not enabled.

### ISSUE THREAD

**Issue by lucashfreitas** [prismicio/gatsby-source-prismic-graphql#17]
Hello,

The plugin currently adds a javascript script by default which can slightly affect the website performance or page speed score. Although we have the option **omitPrismicScript** this is not fully documented clear for most users I think.

If the main purpose of adding the script is to power the preview feature, what if we include it only if the preview is enabled? 

This could be helpful if someone doesn't want to include this script to enable preview directly on production websites and only on stage/development versions. (I am doing that at the moment as page speed is really critical in the project that I am working on).

Another suggestion is to add this option to the documentation.

Please share your thoughts, I am happy to submit a pull request to add docs or implement this change.

![image](https://user-images.githubusercontent.com/11416392/87665550-3463f800-c7bb-11ea-98e1-d115257cbc4c.png)

Thanks

**Comment by ohlr** [comment]
Yep. Also stumbled over this one.
My current solution 
`               const previews = !(process.env.AWS_BRANCH === "master");
`

               previews: previews,
                omitPrismicScript: !previews,

**Comment by ohlr** [comment]
Alternative would be to add `defer` to the point where the script is loaded.

**Comment by MarcMcIntosh** [comment]
Hi @lucashfreitas 
>Please share your thoughts, I am happy to submit a pull request to add docs or implement this change.

Please do :)
