### ISSUE TITLE
[Bug] - Remove Gatsby Image Sharp Image nodes from query

### ISSUE THREAD

**Issue by lucashfreitas** [prismicio/gatsby-source-prismic-graphql#18]
### Context: 

If you use the preview feature and gatsby-image, the `imageSharp` nodes won't be available as the preview feature wraps the component and send the graphql queries on the fly.

The WrapPage component has a `stripSharp` function to remove all sharp nodes. After trying to use the preview feature I realized that the preview graphql query was failing silently logging an error on console that `__fieldSharp` doesn't exists. 

I debugged and realized that the `stripSharp` function is not actually removing all sharp nodes, if you pass a big query with multiple sharp fields it will miss some of them, so the graphql query will fail silently reporting an error on console that sharp field doesn't exist.

After doing tests and reading [traverse documentation] (https://github.com/substack/js-traverse), there is two methods that we can use to remove nodes: `remove` and `delete`. 

As far as I have read the transverse documentation, it seems that we should use the `delete` function as `remove` will splice the element if the parent is an array, which is probably messing the order/removal and leading some sharp fields to not be removed.

### Fix

Replace `remove` call to `delete`

### Tests

As we don't have any tests on the project yet, I set up a codesandbox with a sample for the issue: 
https://codesandbox.io/s/prismic-graphql-strip-sharp-test-popsh?file=/index.test.js

I've also tested it on my local fork and it worked perfectly. It seems that I am close to getting the preview feature 100% functional :)

### Extra Thoughts/Suggestions

The preview feature could maybe display a small popup alerting about errors on graphql query, then would be possible for users to see that something went wrong with the preview. I assume that other people had issues with graphql queries sent by the preview and although we can still see logs in the console would be nice to allow non it users to see bugs and report it to us, otherwise they won't see any updated content on the screen without any alert that something went wrong.

**Comment by Floriferous** [comment]
Hi @lucashfreitas, we're running into this issue too (even though it shouldn't be a preview call... but that's another bug #16 I believe).

What is this `WrapPage` and `stripSharp` function you're talking about? It seems like exactly what we need but I can't find any reference to it in this repo. How do you set this up?

**Comment by lucashfreitas** [comment]
Hello @Floriferous , please reach me out at lucashfreitas1@gmail.com on discord and I can explain to you better. I spent a long time trying to figure out this issue and hopefully can help you with that!
