### ISSUE TITLE
Readingtime of a page

### ISSUE THREAD

**Issue by ohlr** [prismicio/gatsby-source-prismic-graphql#29]
I tried this [plugin](https://github.com/moonmeister/gatsby-plugin-readingtime/issues/4#issuecomment-663630157
) to calculate readingtime serverside but as this plugin apparently uses schema stiching this isn't possible.

https://github.com/moonmeister/gatsby-plugin-readingtime/issues/4#issuecomment-663630157

Any ideas how to compute readingtime server side?

**Comment by MarcMcIntosh** [comment]
Good question, we're aware of the schema stitching issue.

Are you trying to implement incremental builds?

**Comment by ohlr** [comment]
nah, I simply wanted to add an estimate for readingtime to my blogposts...

**Comment by ohlr** [comment]
I'm using the following client side code now:

```
    let allText = "";
    main?.body?.map((slice) => {
        if (slice.type === "text") {
            allText += RichText.asText(slice?.primary?.text) + " ";
        }
    });
    const timeToRead = readingTime(allText);
```
Still would be cool to obtain this via graphql - serverside
