### ISSUE TITLE
414 Request URI too large

### ISSUE THREAD

**Issue by mad-gav** [prismicio/gatsby-source-prismic-graphql#32]
Hi,
I'm facing an issue with a number of pages in that they are failing due to the URI being too large.

![image](https://user-images.githubusercontent.com/60468535/88658209-fa53f980-d0ca-11ea-914f-bcf156945859.png)

Are there any plans to send this payload data as a POST rather than get?

Any workarounds i can implement now?

**Comment by MarcMcIntosh** [comment]
hi @mad-gav 
It has been requested that we use POST requests for graphql, graphql is still a beta feature so maybe this will change but for now it's GET requests only.

The only work around I can think of is trying to reduce character count.
