### ISSUE TITLE
Fresh install throwing error "could not find a copy of gatsby to link..."

### ISSUE THREAD

**Issue by mrseanbaines** [prismicio/gatsby-source-prismic-graphql#39]
Starting a new Gatsby project and installing this package throws an error:

`error An unexpected error occurred: "could not find a copy of gatsby to link in /Users/{path to project}/node_modules/@prismicio/gatsby-source-prismic-graphql/node_modules".`

### Steps to reproduce:
```sh
npx gatsby new prismic-test
cd prismic-test
yarn add @prismicio/gatsby-source-prismic-graphql
```

**Comment by mrseanbaines** [comment]
This seemed to be resolved by downgrading `gatsby`:

```diff
-    "gatsby": "^2.24.37",
+    "gatsby": "2.24.23",
+    "@prismicio/gatsby-source-prismic-graphql": "^3.6.11",
```

No issue with installing other packages on the latest version of Gatsby.

**Comment by MarcMcIntosh** [comment]
Hi @mrseanbaines yes I've notied that using gatsby 2.24.11 works fine, I'm thinking of locking the version in `gatsby-source-graphql-universal` to prevent this from happening
