### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by codebravotech** [prismicio/gatsby-source-prismic-graphql#9]
1. In `gatsby-config.js` you need to have `resolve: '@prismicio/gatsby-source-prismic-graphql'` (as well as in any other examples where the forked repo is pulled in 
2. In the "pages" config array, the individual "previewPath" elements are named "previewPath", whereas in later examples they still say just "path", so it's tough to tell which is which.

**Comment by MarcMcIntosh** [comment]
@codebravotech 
Thanks for pointing that out :)
Fixed [here](https://github.com/prismicio/gatsby-source-prismic-graphql/commit/fc31dc0045ba4faf61032cc9e1cf7e9782dfc500)
